In [1]:
import numpy as np
from sympy.strategies.branch import identity

In [2]:
zero_qubit = np.array([[1],[0]])
one_qubit = np.array([[0],[1]])

In [29]:
qubity = [zero_qubit, one_qubit]

baza = [np.kron(qubity[0], qubity[0]), np.kron(qubity[0], qubity[1]), np.kron(qubity[1], qubity[0])]

In [145]:
baza[0]

array([[1],
       [0],
       [0],
       [0]])

In [108]:
np.kron(np.kron(baza[0], baza[1]), baza[2]).shape

(64, 1)

In [36]:
stan0x0 = np.kron(baza[0], baza[0].conj().T)
stan1x1 = np.kron(baza[1], baza[1].conj().T)
stan2x2 = np.kron(baza[2], baza[2].conj().T)

In [39]:
stan2x2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [42]:
import qiskit.circuit.library as lib
from qiskit.quantum_info import Operator

In [53]:
Z = Operator(lib.ZGate())
X = Operator(lib.XGate())

def Ry(theta):
    return Operator(lib.RYGate(theta))

def P(theta):
    return Operator(lib.PhaseGate(theta))

In [56]:
from numpy.linalg import multi_dot

u1 = multi_dot([X, Ry(np.arctan(1 + np.sqrt(3))), Z, P(np.pi * 3 / 16), X, P(np.pi * 15 / 16)])
u2 = u1
v1 = multi_dot([X, P(np.pi * 3 / 16), X, P(np.pi * 15 / 16), X, Ry(np.arctan(1 + np.sqrt(3))), Z, X])
v2 = multi_dot([X, Z, X, P(np.pi * 9 / 16), X, P(np.pi * 13 / 16), X, Z, Ry(np.arctan(1 + np.sqrt(3)))])

In [57]:
pi = np.pi
sqrt = np.sqrt
log = np.log

common_log_term = log(-1 / 6 * (-1) ** (1 / 4) * (sqrt(24 - 6 * sqrt(3)) + 1j * (3 + sqrt(3))))
common_factor = 3j + 1j * sqrt(3) + sqrt(6 * (4 - sqrt(3)))
denominator = 15 * pi - 4 * 1j * common_log_term

VCx = np.array([
    [
        -(((-1) ** (5 / 8) * common_factor * (30 * pi - 8 * 1j * common_log_term)) / (24 * denominator)) +
        (3 * (-1) ** (5 / 8) * (-30 * pi + 8 * 1j * common_log_term)) / (2 * common_factor * denominator),
        0,
        0,
        (3 * (-1) ** (5 / 8) * (-30 * pi + 8 * 1j * common_log_term)) / (2 * common_factor * denominator) -
        ((-1) ** (5 / 8) * common_factor * (-30 * pi + 8 * 1j * common_log_term)) / (24 * denominator)
    ],
    [
        0,
        -(1 / 2) * (-1) ** (1 / 8) - (1 / 2) * (-1) ** (5 / 8),
        -(1 / 2) * (-1) ** (1 / 8) + (1 / 2) * (-1) ** (5 / 8),
        0
    ],
    [
        0,
        -(1 / 2) * (-1) ** (1 / 8) + (1 / 2) * (-1) ** (5 / 8),
        -(1 / 2) * (-1) ** (1 / 8) - (1 / 2) * (-1) ** (5 / 8),
        0
    ],
    [
        (3 * (-1) ** (5 / 8) * (-30 * pi + 8 * 1j * common_log_term)) / (2 * common_factor * denominator) -
        ((-1) ** (5 / 8) * common_factor * (-30 * pi + 8 * 1j * common_log_term)) / (24 * denominator),
        0,
        0,
        -(((-1) ** (5 / 8) * common_factor * (30 * pi - 8 * 1j * common_log_term)) / (24 * denominator)) +
        (3 * (-1) ** (5 / 8) * (-30 * pi + 8 * 1j * common_log_term)) / (2 * common_factor * denominator)
    ]
], dtype=complex)

In [62]:
fCheck = multi_dot([np.kron(u1, u2), VCx, np.kron(v1, v2)]).round(5)

In [63]:
fCheck 

array([[ 0.57735-0.j ,  0.57735-0.j ,  0.57735-0.j , -0.     -0.j ],
       [ 0.57735-0.j , -0.28868+0.5j, -0.28868-0.5j,  0.     -0.j ],
       [ 0.57735-0.j , -0.28868-0.5j, -0.28868+0.5j,  0.     -0.j ],
       [-0.     -0.j ,  0.     -0.j ,  0.     -0.j ,  1.     -0.j ]])

In [69]:
stanPlusQubity = multi_dot([fCheck, baza[0]])

In [76]:
(stanPlusQubity * np.sqrt(3)).round(3)

array([[1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [0.+0.j]])

In [72]:
stanPlusQudity = np.kron(stanPlusQubity, np.kron(stanPlusQubity, stanPlusQubity))

In [73]:
stanPlusQudity

array([[0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.19244982+0.j],
       [0.        +0.j],


In [88]:
Cz01 = np.kron(stan0x0, fCheck) + np.kron(stan1x1, multi_dot([fCheck, fCheck])) + np.kron(stan2x2, np.identity(4))

In [89]:
CZ01 = np.kron(Cz01, np.identity(4))

In [90]:
CZ01

array([[0.57735+0.j, 0.     +0.j, 0.     +0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j],
       [0.     +0.j, 0.57735+0.j, 0.     +0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j],
       [0.     +0.j, 0.     +0.j, 0.57735+0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j],
       ...,
       [0.     +0.j, 0.     +0.j, 0.     +0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j],
       [0.     +0.j, 0.     +0.j, 0.     +0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j],
       [0.     +0.j, 0.     +0.j, 0.     +0.j, ..., 0.     +0.j,
        0.     +0.j, 0.     +0.j]])

In [91]:
Cz02 = np.kron(np.kron(stan0x0, np.identity(4)), fCheck) + np.kron(np.kron(stan1x1, np.identity(4)), np.identity(4)) + np.kron(np.kron(stan2x2, np.identity(4)), multi_dot([fCheck, fCheck]))


In [92]:
Cz02

array([[ 0.57735+0.j ,  0.57735+0.j ,  0.57735+0.j , ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ],
       [ 0.57735+0.j , -0.28868+0.5j, -0.28868-0.5j, ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ],
       [ 0.57735+0.j , -0.28868-0.5j, -0.28868+0.5j, ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ],
       ...,
       [ 0.     +0.j ,  0.     +0.j ,  0.     +0.j , ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ],
       [ 0.     +0.j ,  0.     +0.j ,  0.     +0.j , ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ],
       [ 0.     +0.j ,  0.     +0.j ,  0.     +0.j , ...,  0.     +0.j ,
         0.     +0.j ,  0.     +0.j ]])

In [93]:
Cz12 = np.kron(np.identity(4), np.kron(stan0x0, np.identity(4)) + np.kron(stan1x1, fCheck) + np.kron(stan2x2, multi_dot([fCheck, fCheck])))

In [94]:
Cz12 

array([[1.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]])

In [96]:
GHZ = multi_dot([CZ01, Cz02, Cz12, stanPlusQudity])

In [149]:
wspolczynnik_zmiany_bazy = np.kron(np.identity(4), np.kron(fCheck.conj().T, fCheck.conj().T))

In [150]:
wspolczynnik_zmiany_bazy.shape

(64, 64)

In [151]:
GHZqubity = multi_dot([wspolczynnik_zmiany_bazy, GHZ])

In [154]:
GHZqubity.round(3)

array([[ 0.192+0.j   ],
       [ 0.192+0.j   ],
       [ 0.192+0.j   ],
       [ 0.   +0.j   ],
       [ 0.333+0.j   ],
       [-0.   +0.j   ],
       [-0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.192+0.j   ],
       [ 0.192+0.j   ],
       [ 0.192-0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.496+0.j   ],
       [ 0.111+0.j   ],
       [ 0.111+0.j   ],
       [ 0.   +0.j   ],
       [ 0.041-0.07j ],
       [-0.056+0.096j],
       [-0.056+0.096j],
       [ 0.   +0.j   ],
       [ 0.041+0.07j ],
       [-0.056-0.096j],
       [-0.056-0.096j],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.   +0.j   ],
       [ 0.496+0.j   ],
       [ 0.111-0.j   ],
       [ 0.111+0.j   ],
       [ 0.   +0.j   ],
       [ 0.041+0.07j ],
       [-0.056-0.096j],
       [-0.056-0.096j],
       [ 0.   +0.j   ],
       [ 0.041-0.07j ],
       [-0.056+0