In [1]:
import numpy as np
from numpy.lib.function_base import interp

In [2]:
qubit0 = np.array([[1],[0]])
qubit1 = np.array([[0], [1]])

In [3]:
qubit0

array([[1],
       [0]])

In [4]:
qudit0 = np.kron(qubit0, qubit0)
qudit1 = np.kron(qubit0, qubit1)
qudit2 = np.kron(qubit1, qubit0)

In [5]:
qubitStan0x0 = np.kron(qubit0, qubit0.conjugate().T)
qubitStan1x1 = np.kron(qubit1, qubit1.conjugate().T)

In [6]:
stan0x0 = np.kron(qudit0, qudit0.conj().T)
stan1x1 = np.kron(qudit1, qudit1.conj().T)
stan2x2 = np.kron(qudit2, qudit2.conj().T)

In [7]:
stan0x0

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
qubitStan0x0

array([[1, 0],
       [0, 0]])

In [10]:
qubitStan1x1

array([[0, 0],
       [0, 1]])

In [119]:
import itertools

def CZgate(control, track):
    final = []
    
    temp = itertools.product([qubitStan0x0, qubitStan1x1], repeat=5)
    
    for i in temp:
        lst = [0] * lst_length
        indexes = list([i for i in range(lst_length) if i != track])
        for idx, val in zip(indexes, i):
            lst[idx] = val
        if np.array_equal(lst[control], qubitStan1x1):
            lst[track] = 'P'
        else:
            lst[track] = 'I'
        final.append(lst)
        
    return final

In [120]:
test = CZgate(3, 4)

In [121]:
len(test)

32

In [123]:
test

[[array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  'I',
  array([[1, 0],
         [0, 0]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  'I',
  array([[0, 0],
         [0, 1]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[0, 0],
         [0, 1]]),
  'P',
  array([[1, 0],
         [0, 0]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[0, 0],
         [0, 1]]),
  'P',
  array([[0, 0],
         [0, 1]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0],
         [0, 0]]),
  array([[0, 0],
         [0, 1]]),
  array([[1, 0],
         [0, 0]]),
  'I',
  array([[1, 0],
         [0, 0]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0],
       