In [1]:
import numpy as np

In [4]:
qubit0 = np.array([[1],[0]])
qubit1 = np.array([[0], [1]])

In [5]:
qubit0

array([[1],
       [0]])

In [6]:
qudit0 = np.kron(qubit0, qubit0)
qudit1 = np.kron(qubit0, qubit1)
qudit2 = np.kron(qubit1, qubit0)

In [120]:
qubitStan0x0 = np.kron(qubit0, qubit0.conjugate().T)
qubitStan1x1 = np.kron(qubit1, qubit1.conjugate().T)

In [41]:
stan0x0 = np.kron(qudit0, qudit0.conj().T)
stan1x1 = np.kron(qudit1, qudit1.conj().T)
stan2x2 = np.kron(qudit2, qudit2.conj().T)

In [42]:
stan0x0

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
def reset(M):
    for i in range(len(M)):
        M[i] = qubitStan0x0
    return M

In [67]:
qubitStan0x0

array([[1],
       [0],
       [0],
       [0]])

In [125]:
qubitStan1x1

array([[0, 0],
       [0, 1]])

In [126]:
temp = np.zeros((2,2,2))
temp[0] = qubitStan0x0

In [127]:
temp

array([[[1., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [162]:
def decomCZ(n, k, l):
    Ph = np.array([[1, 0], [0 , np.exp(np.pi*2/3)]])
    temp = np.zeros((n, 2, 2))
    temp2 = np.zeros((n, 2, 2))
    stany = []
    for i in range(n):
        temp2[i] = qubitStan0x0
        temp2[l] = np.identity(2)
        stany.append(temp2)
    for i in range(n):
        temp = reset(temp)
        print(f'I: {i}')
        print(f'Temp po resecie {temp}')
        temp[i] = qubitStan1x1
        print(f'Po dodaniu 1x1 na indexie {temp}')
        for j in range(len(temp)):
            tempJ = temp
            if i != j:
                print(f'J: {j}')
                tempJ[j] = Ph
                print(f'Po dodaniu j: {tempJ}')
                print(f'tempK {tempJ[k]}')
                if np.array_equal(tempJ[k], qubitStan1x1):
                    tempJ[l] = Ph
                else:
                    tempJ[l] = np.identity(2)
                
                stany.append(tempJ)
            
    return stany

In [163]:
stany2 = decomCZ(3, 0, 1)

I: 0
Temp po resecie [[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]]
Po dodaniu 1x1 na indexie [[[0. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]]
J: 1
Po dodaniu j: [[[0.        0.       ]
  [0.        1.       ]]

 [[1.        0.       ]
  [0.        8.1205274]]

 [[1.        0.       ]
  [0.        0.       ]]]
tempK [[0. 0.]
 [0. 1.]]
J: 2
Po dodaniu j: [[[0.        0.       ]
  [0.        1.       ]]

 [[1.        0.       ]
  [0.        8.1205274]]

 [[1.        0.       ]
  [0.        8.1205274]]]
tempK [[0. 0.]
 [0. 1.]]
I: 1
Temp po resecie [[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]]
Po dodaniu 1x1 na indexie [[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 0.]]]
J: 0
Po dodaniu j: [[[1.        0.       ]
  [0.        8.1205274]]

 [[0.        0.       ]
  [0.        1.       ]]

 [[1.        0.       ]
  [0.        0.       ]]]
tempK [[1.        0.       ]
 [0.        8.1205274]]
J: 2
Po dodaniu j: [[[1.        

In [142]:
for i in stany2:
    print(i)

[[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]
[[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]
[[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]
[[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]
[[[1. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]


In [143]:
len(stany2)

5

IndexError: list index out of range