In [4]:
import numpy as np

In [6]:
omega = np.exp(2*np.pi*1.j/3)
Z = np.array([[1, 0, 0, 0], [0, omega, 0, 0], [0, 0, omega*omega, 0], [0, 0, 0, 1]])
X = np.array([[0,0,1,0], [1,0,0,0], [0,1,0,0],[0,0,0,1]])

In [3]:
X

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [4]:
X.conjugate().transpose()

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [9]:
G1 = np.kron(Z, np.kron(Z, X))
G2 = np.kron(Z, np.kron(X, np.identity(4)))
G3 = np.kron(Z, np.kron(np.identity(4), X))

In [11]:
from qiskit.quantum_info import Statevector

In [2]:
from QuditsOnQubits import QuditsOnQubits

ModuleNotFoundError: No module named 'qiskit_aer'

In [13]:
a1 = Statevector().from_label("000000")

TypeError: __init__() missing 1 required positional argument: 'data'

In [16]:
ghz = QuditsOnQubits()

TypeError: 'module' object is not callable

In [36]:
Zq = np.array([[1, 0, 0], [0, omega, 0], [0, 0, omega*omega]])
Xq = np.array([[0,0,1], [1,0,0], [0,1,0]])

In [44]:
G1q = np.kron(Xq, np.kron(Zq, Zq)).round(3)

In [45]:
G1qH = G1q.conjugate().transpose().round(3)

In [46]:
np.array_equal(G1q, G1qH)

False

In [32]:
qutryt0 = [[1], [0], [0]]
qutryt1 = [[0], [1], [0]]
qutryt2 = [[0], [0], [1]]   

In [39]:
np.dot(Xq, qutryt2)

array([[1],
       [0],
       [0]])

In [47]:
G1q

array([[ 0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  1. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ],
       [ 0. +0.j   , -0. +0.j   ,  0. +0.j   ,  0. +0.j   , -0. +0.j   ,
         0. +0.j   ,  0. +0.j   , -0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
        -0. +0.j   ,  0. +0.j   ,  0. +0.j   , -0. +0.j   ,  0. +0.j   ,
         0. +0.j   , -0. +0.j   ,  0. +0.j   ,  0. +0.j   , -0.5+0.866j,
         0. +0.j   ,  0. +0.j   , -0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
        -0. +0.j   ,  0. +0.j   ],
       [ 0. +0.j   ,  0. +0.j   ,  0. -0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,  0. +0.j   ,
         0. +0.j   ,  0. -0.j   ,  0. +0.j   ,  0. +0.

In [48]:
G1qH

array([[ 0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  1. -0.j   ,
         0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   ,  0. -0.j   ],
       [ 0. -0.j   , -0. -0.j   ,  0. -0.j   ,  0. -0.j   , -0. -0.j   ,
         0. -0.j   ,  0. -0.j   , -0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
        -0.5-0.866j,  0. -0.j   ,  0. -0.j   , -0. -0.j   ,  0. -0.j   ,
         0. -0.j   , -0. -0.j   ,  0. -0.j   ,  0. -0.j   , -0. -0.j   ,
         0. -0.j   ,  0. -0.j   , -0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
        -0. -0.j   ,  0. -0.j   ],
       [ 0. -0.j   ,  0. -0.j   ,  0. +0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,  0. -0.j   ,
         0. -0.j   , -0.5+0.866j,  0. -0.j   ,  0. -0.